[tool.poetry]
name = "my-ocr-deepseek-ocr"
version = "0.1.0"
description = ""
authors = ["RynGhd <ryan.ghadiri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
